### ISSUE TITLE
经常在打开画廊时显示memory error

### ISSUE THREAD

**Issue by CateneX** [Gandum2077/PyEhViewer#3]

**Comment by Gandum2077** [comment]
请提供详细信息

**Comment by CateneX** [comment]
设备: iPad mini 5th
系统版本: 13.3
Pythonista版本: 3.3
软件版本: 2.0

在搜索界面点击任意画作图片时大概率出现如图片所示memory error
其他功能均正常
![BVXXV6L UE78`IL M$Q$Y0O](https://user-images.githubusercontent.com/42759780/77629886-2d537880-6f85-11ea-9206-8c32ed5d536b.jpg)

**Comment by Gandum2077** [comment]
你目前给的信息不能帮助定位问题，请先把Traceback贴上来看看

**Comment by cajpek** [comment]
同样的问题
设备: iPad Air 3th
系统版本: 13.3.1
Pythonista版本: 3.3
软件版本: 2.0

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/7D1FD146-4D11-4DB2-8F1C-533B1C6EEFD9/Pythonista3/Documents/PyEhViewer/core/listview.py", line 560, in open_gallery
    galleryview(self.url)
  File "/private/var/mobile/Containers/Shared/AppGroup/7D1FD146-4D11-4DB2-8F1C-533B1C6EEFD9/Pythonista3/Documents/PyEhViewer/core/galleryview.py", line 789, in galleryview
    v.xdid_load(url)
  File "/private/var/mobile/Containers/Shared/AppGroup/7D1FD146-4D11-4DB2-8F1C-533B1C6EEFD9/Pythonista3/Documents/PyEhViewer/core/galleryview.py", line 92, in xdid_load
    self.refresh()
  File "/private/var/mobile/Containers/Shared/AppGroup/7D1FD146-4D11-4DB2-8F1C-533B1C6EEFD9/Pythonista3/Documents/PyEhViewer/core/galleryview.py", line 104, in refresh
    self.add_subview(self._render_scrollview())
  File "/private/var/mobile/Containers/Shared/AppGroup/7D1FD146-4D11-4DB2-8F1C-533B1C6EEFD9/Pythonista3/Documents/PyEhViewer/core/galleryview.py", line 144, in _render_scrollview
    comments_view = self._render_comments_view()
  File "/private/var/mobile/Containers/Shared/AppGroup/7D1FD146-4D11-4DB2-8F1C-533B1C6EEFD9/Pythonista3/Documents/PyEhViewer/core/galleryview.py", line 165, in _render_comments_view
    v = CommentsView(self.info)
  File "/private/var/mobile/Containers/Shared/AppGroup/7D1FD146-4D11-4DB2-8F1C-533B1C6EEFD9/Pythonista3/Documents/PyEhViewer/core/galleryview.py", line 459, in __init__
    text=self.get_comments_text()
  File "/private/var/mobile/Containers/Shared/AppGroup/7D1FD146-4D11-4DB2-8F1C-533B1C6EEFD9/Pythonista3/Documents/PyEhViewer/core/galleryview.py", line 484, in get_comments_text
    text = i['posted_time'] + ' by ' + i['commenter'] + ', ' + c4text + '\n\n' + html2text_engine.handle(i['comment_div']).strip()
  File "/var/containers/Bundle/Application/1705B664-DDBE-42F1-8881-3C1FD3C7219B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/html2text.py", line 276, in handle
    return self.optwrap(self.close())
  File "/var/containers/Bundle/Application/1705B664-DDBE-42F1-8881-3C1FD3C7219B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/html2text.py", line 289, in close
    self.outtext = self.outtext.join(self.outtextlist)
MemoryError

**Comment by Gandum2077** [comment]
已确认是html2text版本的问题

解决方案：使用stash安装新版html2text

**Comment by Gandum2077** [comment]
此问题不是本应用本身能够解决的，需要升级依赖html2text，我已在README中注明
