### ISSUE TITLE
 Non-ASCII character '\xe9'

### ISSUE THREAD

**Issue by nil-err** [Gandum2077/PyEhViewer#4]
第一次运行main.py时出现错误，
设备: iPad Air 3th
系统版本: 13.4.5
Pythonista版本: 3.3(330025)
软件版本: 2.0

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/B0DBD832-8E48-4915-B404-B265CE509A1A/Pythonista3/Documents//PyEhViewer/main.py", line 4, in <module>
    from parse.exhentaiparser import CONFIGPATH, COOKIE_FILE
  File "/private/var/mobile/Containers/Shared/AppGroup/B0DBD832-8E48-4915-B404-B265CE509A1A/Pythonista3/Documents/PyEhViewer/parse/exhentaiparser.py", line 45
SyntaxError: Non-ASCII character '\xe9' in file /private/var/mobile/Containers/Shared/AppGroup/B0DBD832-8E48-4915-B404-B265CE509A1A/Pythonista3/Documents/PyEhViewer/parse/exhentaiparser.py on line 45, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by nil-err** [comment]
已经解决了，这个软件main.py要在python3下运行
